# Generated by Django 4.1.3 on 2022-11-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="angry_database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.TextField()),
                ("phrase", models.TextField()),
                ("authorPic", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="happy_database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.TextField()),
                ("phrase", models.TextField()),
                ("authorPic", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="nervous_database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.TextField()),
                ("phrase", models.TextField()),
                ("authorPic", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="sad_database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.TextField()),
                ("phrase", models.TextField()),
                ("authorPic", models.TextField()),
            ],
        ),
    ]
